CREATE TABLE `relatorios` (
	`id` int AUTO_INCREMENT NOT NULL,
	`encarregado_nome` varchar(255) NOT NULL,
	`encarregado_sobrenome` varchar(255) NOT NULL,
	`encarregado_patente` varchar(50) NOT NULL,
	`viatura_prefixo` varchar(50) NOT NULL,
	`chefe_barca_patente` varchar(50) NOT NULL,
	`chefe_barca_nome` varchar(255) NOT NULL,
	`motorista_patente` varchar(50) NOT NULL,
	`motorista_nome` varchar(255) NOT NULL,
	`terceiro_homem_patente` varchar(50) NOT NULL,
	`terceiro_homem_nome` varchar(255) NOT NULL,
	`quarto_homem_patente` varchar(50) NOT NULL,
	`quarto_homem_nome` varchar(255) NOT NULL,
	`quinto_homem_patente` varchar(50) NOT NULL,
	`quinto_homem_nome` varchar(255) NOT NULL,
	`data_inicio` timestamp NOT NULL,
	`data_fim` timestamp NOT NULL,
	`total_ocorrencias` int NOT NULL DEFAULT 0,
	`drogas_apreendidas` int NOT NULL DEFAULT 0,
	`dinheiro_sujo_apreendido` bigint NOT NULL DEFAULT 0,
	`armamento_apreendido` int NOT NULL DEFAULT 0,
	`municao_apreendida` int NOT NULL DEFAULT 0,
	`bombas_apreendidas` int NOT NULL DEFAULT 0,
	`lockpik_apreendidas` int NOT NULL DEFAULT 0,
	`relacao_detidos_bos` text,
	`acoes_realizadas` text,
	`observacoes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `relatorios_id` PRIMARY KEY(`id`)
);
